server:
  port: 8100
###服务注册名称
eureka:
  instance:
    #注册中心ip地址
    hostname: 127.0.0.1
  ###客户端调用地址
  client:
    serviceUrl:
      #注册地址
      defaultZone: http://${eureka.instance.hostname}:9100/eureka/
    ###因为该应用为注册中心，是否需要将自己注册给自己，（集群的时候需要为true）
    register-with-eureka: true
    ###因为自己为注册中心 ,不会去在该应用中的检测服务
    fetch-registry: true
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
  server:
    enable-self-preservation: false
    ##剔除失效服务间隔 2s
    eviction-interval-timer-in-ms: 2000



### 一定要定义服务名称，且集群的名称全部相同
spring:
  application:
    name: springcloud-erueka


